# Generated by Django 5.2.2 on 2025-06-07 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_month_year', models.CharField(max_length=20)),
                ('frontend_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('backend_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending_verification', 'Pending Verification'), ('rejected', 'Rejected')], default='pending_verification', max_length=30)),
                ('verification_details', models.TextField(blank=True)),
                ('actions_required', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='clients.client')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
