# Generated by Django 5.2.2 on 2025-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_projectstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry_type',
            field=models.CharField(choices=[('web_design', 'Web Design & Development'), ('real_estate', 'Real Estate'), ('home_decor', 'Home Decor'), ('studio_accessories', 'Studio Accessories'), ('handloom', 'Handloom'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='project_handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='actions_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='verification_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
